### ISSUE TITLE
Add 'split_libraries' to the pipeline

### ISSUE THREAD

**Issue by bhillmann** [knights-lab/shi7#11]
This is similar to the QIIME [split_libraries_fastq.py](http://qiime.org/scripts/split_libraries_fastq.html)

This source is included [here](https://github.com/knights-lab/shi7en/blob/master/src/gotta_split_swapped.c).

This should be the first step in the pipeline. It should default to False. User must provide TXT file of oligos. Should be a command line argument. Will split combined FASTQ file into individual FASTQs per sample.

**Comment by bhillmann** [comment]
There is a wiki link for describing how the oligos.txt file should look.

What if I have one giant fastq (well, one pair -- an R1 and R2) I want to split into samples?` Excellent you should ask. Use [G0774_5PL17](https://github.com/GabeAl/NINJA-SHI7/blob/master/others/gotta_split.c) ("gotta_split") with an oligos.txt file to create multiple fastq's, one for each sample name (see: http://www.mothur.org/wiki/Oligos_File#Paired_Barcodes). Only PAIRED BARCODE is supported, without "None."

**Comment by kaiweiang** [comment]
What's the `gotta_split` command like? Is it just like `gotta_split_linux -i oligos.txt`?

**Comment by bhillmann** [comment]
That is correct. It is the command with the binaries linked. Ask @GabeAl for the most up to date source and how to create a Makefile/compile the code.

**Comment by kaiweiang** [comment]
@GabeAl

**Comment by kaiweiang** [comment]
Need to update readme to tell the users how to use the split option.

**Comment by bhillmann** [comment]
@GabeAl 

Can you verify that we can specify an output folder with the:

```
gotta_spli7 -i <input_fastq> -o <output_fastq>
```

**Comment by GabeAl** [comment]
Usage: gotta_split r1.fq r2.fq oligos.txt [PREFIX] [--deep] [--errors N]

**Comment by kaiweiang** [comment]
[PREFIX] is the output folder. E.g. [folder_name/]

**Comment by kaiweiang** [comment]
@GabeAl I don't have any testing files for gotta_split. Can you provide some?

**Comment by GabeAl** [comment]
[gotta_test.zip](https://github.com/knights-lab/shi7en/files/657804/gotta_test.zip)

**Comment by GabeAl** [comment]
Also see: https://github.com/knights-lab/shi7en/commit/1746fe4e34a989269a87ba1e1c2e7652e6d98d56#commitcomment-20220253

**Comment by GabeAl** [comment]
Couple comments: I'd suggest the following commands for the gotta_split component as arguments for shi7en.py:
--split_r1
--split_r2
--split_oligos
--split_output

This way they'll be clear and easy to fit into the use categories that gotta split has:
Usage: gotta_split r1.fq r2.fq oligos.txt [PREFIX] [--deep] [--errors N]

so it would be gotta_split <split_r1> <split_r2> <split_oligos> <split_output>

Sound good? :+1:

**Comment by kaiweiang** [comment]
@GabeAl The small samples you gave me (uploaded in this thread) last time did not work, and I think it is because the oligos.txt did not match with the R1 and R2 samples. I can only test it if you give me the access to the remote machine where you test it, like you said you're going to in another thread.

**Comment by kaiweiang** [comment]
Regarding the comments, the extra flags I set up are
--split_r1
--split_r2
--split_output
The oligos is treated as the --input arguments, since the --input flag is the **required flag** and there will not have input directory if the users want to run gotta_split. In the end of the gotta split, the output of gotta_split will be the new input for the subsequent steps. Ofc, the instructions need to be added to the readme.

**Comment by GabeAl** [comment]
Thanks! I'm going to close this for now until any new bugs or issues are reported. I will update the help strings and (eventually) the readme!
