### ISSUE TITLE
SE mode with Nextera calls Nextera PE adaptors

### ISSUE THREAD

**Issue by RRShieldsCutler** [knights-lab/shi7#18]
Appears to be fine with other adaptors, but when using "-SE --adaptor Nextera" it calls:
shi7en/adapters/NexteraPE-PE.fa:2:30:10:2:true

whereas for TruSeq3, it calls:
/shi7en/adapters/TruSeq3-SE.fa:2:30:10:2:true

**Comment by bhillmann** [comment]
There is no such thing as Nextera single end adapters. The paired end adapters file in theory should work just fine, since they include both forward and reverse adapters.

Check them out [here](https://github.com/knights-lab/shi7en/tree/master/shi7en/adapters).
