### ISSUE TITLE
rename "trim" to "filter"

### ISSUE THREAD

**Issue by danknights** [knights-lab/shi7#21]
"trim" usually means cut sequence length.

**Comment by GabeAl** [comment]
Where?

 parser.add_argument('--trim', help='Enable (True) or Disable (False) the TRIMMER (default: True)', choices=[True,False], default='True', type...)

This guy calls the binary shi7 c trimmer (which also happens to act as a filter). There is also an adapter trimming via trimmomatic. Which instance of "trim" do you mean?

Thanks!

**Comment by bhillmann** [comment]
-l_trim is the flag we were working with.

**Comment by GabeAl** [comment]
Oh, this one then:

parser.add_argument('-trim_l', '--trim_length', help='Set the trim length (default: %(default)s)', default=150, type=int)

Yeah makes sense! It's supposed to filter out reads below this length, not trim longer ones to 150 bases.

**Comment by kaiweiang** [comment]
@GabeAl so should we change trim_length to filter?
