### ISSUE TITLE
Not correctly pairing reverse and forward reads

### ISSUE THREAD

**Issue by Bryan-S-Featherstone** [knights-lab/shi7#22]
12/14/2016 01:50:38 PM flash Bioko_Table/temp/axe/ML04.S305.R1.fastq Bioko_Table/temp/axe/MLK01.S299.R2.fastq -o ML04.S305 -d Bioko_Table/temp/flash -M 700 -m 20 -t 48 -O
12/14/2016 01:50:39 PM [FLASH] Starting FLASH v1.2.11
[FLASH] Fast Length Adjustment of SHort reads
[FLASH]
[FLASH] Input files:
[FLASH]     Bioko_Table/temp/axe/ML04.S305.R1.fastq
[FLASH]     Bioko_Table/temp/axe/MLK01.S299.R2.fastq

**Comment by bhillmann** [comment]
@kaiweiang  This has to do with the split forward and reverse function. I'm not entirely sure why sorting them doesn't cause them to pair. Can you take a look at this?

**Comment by bhillmann** [comment]
It looks like sorting does work.
