### ISSUE TITLE
Limit default threads to 16

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#23]
On most machines with hard drives, I/O starts to become the bottleneck and the software actually slows down with more threads. The user can still set whatever they like, but adding something like:

defaults = max(mp.getNumThreads(),16) for the default would be helpful :)

**Comment by kaiweiang** [comment]
Ya, I just tried it on my local Mac machine. It turned out the fewer the number of threads, the faster it ran. 4 threads ran faster than 16 threads though. @GabeAl
