### ISSUE TITLE
Threads are not respected -- wrong number of threads used

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#24]
Hi,

Bryan tried running it specifying -t 46 but trimmomatic is using 256 threads.

Possibilities: 
- passing it as a string instead of an integer? 
- formatting problems
- trimmomatic is buggy

**Comment by kaiweiang** [comment]
I tried it on my mac with -t 46 and it worked. Can we see his shi7en.log?

**Comment by GabeAl** [comment]
http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf

**Comment by kaiweiang** [comment]
@GabeAl Can you test it again?

**Comment by GabeAl** [comment]
Seems to work -- though we should still try with a collaborator's machine. 

Kaiwei, I'm going to give you access to my linux machine to try it out on your end too!

**Comment by GabeAl** [comment]
Closing as it seems to work (will re-open if the issue ever re-emerges!)
