### ISSUE TITLE
test whether this works with spaces in the directory names

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#26]
(Ensure there are quotes around every directory/file location passed to the programs)

**Comment by GabeAl** [comment]
The simple answer to this question would probably also be the answer to this one:
Does os.path.join put quotes around the string it returns [or delimit spaces with '\ ']? If yes, spaces should be fine.

**Comment by bhillmann** [comment]
I'm not entirely sure of the behavior of os.path.join, so let us check it out. It is meant to be system agnostic, so my guess is that it does work with spaces.

```python
>>> os.path.join('space in a dir', 'space in a file.txt')
'space in a dir\\space in a file.txt'
```

And voila, it works.
