### ISSUE TITLE
Self-learning methods

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#28]
A primary feature that can set this software apart from other pipelines could be its ability to learn what parameters to use based on the fastq data it is provided. To do this, the user should specify a "learning" mode, and the software should figure out the parameters, and explain to the user what selections have been made.

- Look at the names of the files and determine whether R1 and R2 are likely to be present. If unlikely (when sorted, files have different numbers of lines, or there's no "1" changing to "2" in the next alphabetical file), disable paired end mode.

Presumably we can accomplish a lot of the more intricate "self-learning" methods easily if we do this one thing: Make a "testbed" function that grabs 10,000 reads (or a single sample, whatever comes first) of a single input pair (if paired-end) or R1 fastq (if not paired-end) and do the following on it:
- Try all adapters; read the resulting filesizes; choose the adapters that made the smallest files
- Try stitching: if fewer than 20% stitch at the default minimum overlap of 15, disable flash
- If stitching works: read the histogram file and calculate median and standard deviation. If standard deviation is less than a fourth of the mean, clamp the stitching min and max to [mode - 10, mode + 10].
- If stitching is disabled, increase the stringency of shi7_trimmer trimming to get rid of the bad-quality tails (the defaults expect stitching and are designed to just lop off straggling adapters, not chew off large stretches of the read). 

Yes, we really _can_ distill this art into a science, and all automatically while reporting to the user what we did, and only if the user elects to use the "learning" mode. :)

**Comment by bhillmann** [comment]
Seems feasible enough.

I am concerned with the first step with the adapters. Wouldn't you rather look at consistency of trimming based on length of trim?

Can you more explicitly define 'low quality' tails?

**Comment by bhillmann** [comment]
R1/R2 can be determined by filesize.

**Comment by GabeAl** [comment]
Now in place as of 0.9.3!
