### ISSUE TITLE
SHI7EN on MSI

### ISSUE THREAD

**Issue by pvangay** [knights-lab/shi7#30]
(shi7en) vanga015@labc03 [~/imp] % pip install git+https://github.com/knights-lab/shi7en --upgrade --no-cache-dir
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007f1b16ffe700 (most recent call first):
Aborted (core dumped)
(shi7en) vanga015@labc03 [~/imp] % 
qsub: job 478001.nokomis0015.msi.umn.edu completed
Connection to lab closed.

**Comment by bhillmann** [comment]
I believe this is a bug with your installation of Python and not SHI7EN. 

There are most likely multiple versions of Python installed on your account for MSI. Can you try running:

```
which python
```

With your environment active? Then, you should see where pip is installing its libraries. It should be to the conda environment. More information about this issue can be found [here](https://techglimpse.com/error-executing-python3-5-command-solution/).

**Comment by GabeAl** [comment]
We should prioritize getting conda/env-free installation working for a preliminary 1.0. As much as I love environments, I think for simplicities sake (and to save ourselves the debugging hassle for early versions like the pip/conda fiasco that plagued Byran's setup), we should wrangle something up. I'm working on a distributable for linux now (we will set this up as our lab SOP too!)

**Comment by GabeAl** [comment]
Try with the new release package and let me know. 

(i.e. if it requires chmod +x on everything in the dir or whatever)

**Comment by GabeAl** [comment]
Try with the new version 0.91 on releases, or add this to your path:
```
module load python2
PATH=$PATH:/home/knightsd/algh0022/sop
```

and then re-load your environment. You should be able to use shi7.py normally!

**Comment by bhillmann** [comment]
This should be fixed, closing for now.
