### ISSUE TITLE
sample name editing

### ISSUE THREAD

**Issue by pvangay** [knights-lab/shi7#31]
Files from UMGC are oddly named like this: "T-CS-147_S118_L001_R1_001.fastq"

But my actual sample name is only "T.CS.147"

At the moment SHI7EN turns this into T.CS.147.S118

Is there any way to specify where the sample name starts/stops?

**Comment by bhillmann** [comment]
Not at this time, it does this for QIIME formatting.

**Comment by GabeAl** [comment]
A simple fix would be to add an option like "--truncate_names" which would only keep filenames up to the first underscore "_" character. So for example if one of our files was named: 

Bla.blablab-Blabla_Bla_001_S2183_R1_001.fastq 

Then for making the names in the fasta file, we should only keep: Bla.blablab.Blabla. 

Easy way: 
str.split('_')[1]
To grab the string before the underscore. Then continue with parsing as normal (replace non alphanumeric characters with dot and so forth).

**Comment by bhillmann** [comment]
Sure we can add that!

I'm entirely unsure of the scope of how much these one off features will be needed though. Do we have evaluation criteria for adding features? We are already quickly filling up with a lot of commandline arguments. I'm all about promoting flexibility, but having to maintain this functionality over regressions could turn out to be a pain.

Should we enact a more stable 'metadata' file format for SHI7EN? It would be trivial to implement, but could alleviate this issue.

**Comment by pvangay** [comment]
Well, I think that since most of our raw sequences for the entire lab will be coming from UMGC, it would be nice if the default behavior for SHI7EN worked best for those files. But I'm open to any solution - as long as there is one. 

Thanks y'all!

**Comment by bhillmann** [comment]
Very fair point. What would you like it to do?

The file names are like:

"T-CS-147_S118_L001_R1_001.fastq"

And then they should be output like:

"T-CS-147_S118_L001_R1_001.fasta"

Or if you stitch...

"T-CS-147_S118_L001.fasta"

**Comment by GabeAl** [comment]
So the goal is to keep T.CS.147 and nothing else. So kill all at the first underscore (an option for this might be more generally useful than we thought, too -- Trevor mentioned this is a convention for naming plates/wells the sample went into).

**Comment by GabeAl** [comment]
Added functionality to python for this -- but it is half-baked for now, so don't use it yet. 

Needs a revamp of the functions (passing around dozens of arguments is Very Bad News for any changes to a core function's arg count. Instead, pass around the args object or another object of relevant variables such as a list). 

To-do: remove global variable, make it work when the R1 appears before the first underscore

**Comment by bhillmann** [comment]
I agree, there shouldn't be any global variables. Functions should be written to be modular, such that they only take in a set of few arguments and work within their defined scope. Can you show me what your issue is? Everyone making changes to the code should be doing so with an interactive programming environment set up, so they can see what variables are in the scope. We also should set up some sort of testing so that regressions that need to be satisfied can be tracked. The project is becoming larger so it is a good time to set that up now. There really isn't any global variables that I am aware of.

**Comment by GabeAl** [comment]
Update: PJ's request is in. Additionally, rolled back the other core-specific mods since we can't rely on them (should they be enable-able? "sanitize" options?). 

To use this feature, use "-s" or "--strip_underscore" which will strip the first underscore and everything after it. Let me know!
