### ISSUE TITLE
Remove dependence on string "R1" occurring in reads

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#33]
Code in question:
`format_basename(re.sub('R1', '', input_path_R1))`
This needs to change (or add a check if R1 is not present, just to swap "1"). I don't know whether this would cause downstream problems after stitching if the reads didn't contain "R1" or "R2" but instead had .1 and .2 or F and R or some other convention that is now caught properly with the new trimmo paired end even-odd selector.

**Comment by bhillmann** [comment]
It shouldn't cause any downstream issues. Every function is modular and only uses local scope.

**Comment by GabeAl** [comment]
That's not what I mean. For example, if this particular function depends on
finding the string "R1" and it doesn't exist because it uses a different
format (like the HMP .1. or .2.), what will happen? Dependencies are
carried through the modification of fastq_path and if this step expects
something others don't, it's worrisome.

Other functions now just sort and take even numbers as R1 and odd as R2
which gets around direct pattern matching like this. Would be nice to
revamp for consistency

**Comment by GabeAl** [comment]
May be related to #42

**Comment by GabeAl** [comment]
Going to close this as it doesn't seem to be an issue anymore. Other issues involving R1/R2 may have been conflated with this one!
