### ISSUE TITLE
Rename all 'ninja_shi7' to 'shi7en'

### ISSUE THREAD

**Issue by bhillmann** [knights-lab/shi7#4]
We are removing the 'ninja' prefix from this project.

**Comment by bhillmann** [comment]
@kaiweiang Is this complete?

**Comment by kaiweiang** [comment]
@bhillmann I think so iirc, but I'll check again in the evening.

**Comment by kaiweiang** [comment]
@bhillmann I think so iirc, but I'll check again in the evening. I'll close this once I confirm.
