### ISSUE TITLE
Bug: filenames mutated containing R1 and R2 in sample names

### ISSUE THREAD

**Issue by GabeAl** [knights-lab/shi7#49]
'ERR1352369', 'ERR1352368', 'ERR1352367', 'ERR1352366', 'ERR1352365', 'ERR1352364', 'ERR1352363', 'ERR1352362', 'ERR1352361', 'ERR1352360', 'ER368486', 'ER368487', 'ER368484', 'ER368485', 'ERR989659', 'ERR989658', 'ER368480', 'ER368481', 'ERR989657', 'ER368488', 'ER368489', 'ER368507', 'ER368506', 'ER368505', 'ER368504', 'ER368503', 'ER368502', 'ER368501', 'ER368500', 'ER368509', 'ER368508', 'ER368491', 'ERR688806', 'ER368499', 'ER368498', 'ERR1352370', 'ER368490', 'ER368493', 'ER368492', 'ER368495', 'ER368494', 'ER368497', 'ER368496', 'ERR989664', 'ERR989665', 'ERR989666', 'ERR989667', 'ERR989660', 'ERR989661', 'ERR989662', 'ERR989663', 'ERR989668', 'ERR1352359', 'ER368514', 'ER368515', 'ER368516', 'ER368517', 'ER368510', 'ER368511', 'ER368512', 'ER368513', 'ERR576948', 'ER368518', 'ER368479', 'ER368482', 'ER368483']

The last file, for instance, was ERR1368483_1. (Notice it has an embedded "R1" by chance) I think we need a smarter way of parsing these guys... or a way to explicitly add R1/R2 to files that are detected as pairs (if they were detected as such without "R1/R2" being the determinant. 

The way it is now, regardless of how files are paired, "R1" is naively searched for and stripped in all files regardless if they're R1's, or R2's, or if they even had R1/R2 in the name to begin with, and in this case it's indiscriminate -- whether the R1 is in the beginning or end of the file etc. 

The proposed solution is:
1. Determine whether prospective pairs contain R1 and R2 in the same position in their filenames and matches what we expect. 
1b. If not, add R1/R2 to the ends of the filenames.
2. In subsequent processing steps, strip only the *final* R1/R2 in the names at the very end. Don't strip all occurrences of R1/R2 strings in all files indiscriminately at every step.

**Comment by RRShieldsCutler** [comment]
Yes, along with point 1, would be nice to detect if labeled with just "1" not "R1", etc. by matching pairs. Part 2 is straightforward once 1 is done.

Would be nice if file names were just consistent.......

**Comment by RRShieldsCutler** [comment]
@GabeAl  What was the command run for the issue described above?

**Comment by GabeAl** [comment]
This was the standard run with -i and -o and --adaptor Nextera

(so it does the stitching and R1/R2 detection stuff!)

**Comment by GabeAl** [comment]
Should be fixed!
