### ISSUE TITLE
Index out of range error on FLASH outies in test data

### ISSUE THREAD

**Issue by transcript** [knights-lab/shi7#58]
I just downloaded the latest release (0.9.9), unzipped, and ran the following command:

`shi7_learning.py -i testfq -o learnt`

and got the following error:

```
Traceback (most recent call last):
  File "/home/dnanexus/shi7/shi7_learning.py", line 379, in <module>
    main()
  File "/home/dnanexus/shi7/shi7_learning.py", line 330, in main
    stitches, do_outies, fastq_paths = flash_stitchable_and_check_outies(fastq_paths, stitched_path, int(args.threads))
  File "/home/dnanexus/shi7/shi7_learning.py", line 137, in flash_stitchable_and_check_outies
    outies_info = flash_str_list[-8]
IndexError: list index out of range
```

Not sure what's wrong, but this seems pretty darn reproducible!

**Comment by GabeAl** [comment]
Thanks Sam!

Could you please post the log file? The python errors are usually not useful, sadly. 

I imagine it could be a problem with the flash binary. Is it set executable and properly added to your PATH environment variable? (See the non-conda installation instructions for details on this!)

Thanks for the report!

**Comment by transcript** [comment]
Sure thing.  I'm attaching it here.  I don't see an error in it directly.

[shi7_learning.log](https://github.com/knights-lab/shi7/files/2054984/shi7_learning.log)

**Comment by GabeAl** [comment]
Thanks! The log says you don't have Java, which is a prerequisite for
running shi7 with trimmomatic.

You can get away with no Java if you forego the learning step and any
adaptor removal.

Let me know if you need any help setting up Java or example commands that
forego adaptor removal!

Cheerio,
Gabe

**Comment by transcript** [comment]
Ah, that's an easy enough fix!  Let me install Java quick and retry, and I'll close this if things proceed.

**Comment by GabeAl** [comment]
Cool!
The link for the sdk is on the main Github page and the readme, can't miss
it! Fingers crossed! 🤞

**Comment by transcript** [comment]
Looks like installing Java fixed the issue, and everything ran successfully.
