### ISSUE TITLE
Legacy variable from v0.9.9 exists in v1.0.0, raises NameError

### ISSUE THREAD

**Issue by wigasper** [knights-lab/shi7#66]
Line 249 of `shi7_learning.py` uses the `VERSION` variable, but this was replace v1.0.0 with `__version__`, this causes a NameError and the script fails. See my [pull request](https://github.com/knights-lab/shi7/pull/65/commits/080c7ed798400857a02c7e6cafc778aa8301255e)

**Comment by wigasper** [comment]
Hi! Thanks a bunch for doing this, I am only now concerned because it looks like the pull request that came after this would have fixed that because it imports version information as VERSION, so now actually my PR breaks it

**Comment by GabeAl** [comment]
Hi,

Yes -- I've noticed a bit too late there were a few merge issues here
(merged in things that seemed conflict-free but were in fact based on
different code-bases), so I'm trying to unify now. I issued a couple of
band-aids, but if you catch anything now, let me know! Much appreciated.

Thanks,
Gabe
